import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <div className="flex bg-slate-200 p-5">
          <Link href="/" className="mr-5">
            Next.js
          </Link>
          <Link href="/users" className="mr-5">
            Users
          </Link>
        </div>
        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
